include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  # Analyze tests with the same lints as the package code.
  # Add targeted ignores here if any golden harness files require it.
