name: dashronym
description: Inline glossary tooltips for acronyms in Flutter text.
version: 0.0.9
homepage: https://pub.dev/packages/dashronym
repository: https://github.com/chrismercredi/dashronym/
issue_tracker: https://github.com/chrismercredi/dashronym/issues
topics:
  - text
  - tooltip
  - documentation
  - acronyms
  - a11y

screenshots:
  - description: 'Animated overview of Dashronym tooltips responding to user taps.'
    path: screenshots/0_dashronym.gif
  - description: 'Landscape tooltip showcasing custom builder content.'
    path: screenshots/1_dashronym_landscape_tooltip_builder.png
  - description: 'Landscape tooltip constrained within the viewport.'
    path: screenshots/2_dashronym_landscape_tooltip.png
  - description: 'Portrait tooltip with viewport-safe positioning.'
    path: screenshots/3_dashronym_portrait_tooltip.png

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
