name: dashronym
description: Inline glossary tooltips for acronyms in Flutter text.
version: 0.0.6
homepage: https://pub.dev/packages/dashronym
repository: https://github.com/chrismercredi/dashronym/
issue_tracker: https://github.com/chrismercredi/dashronym/issues
topics:
  - text
  - tooltip
  - documentation

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
